apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-monitor
  namespace: monitor
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    requests.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-application
  namespace: application
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    requests.memory: 4Gi