alertmanager:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

  ingress:
    enabled: true
    pathType: Prefix
    hostname: alertmanager.prometheus.local
    ingressClassName: nginx
  
  service:
    type: ClusterIP

server:
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  ingress:
    enabled: true
    pathType: Prefix
    hostname: prometheus.local
    ingressClassName: nginx
  
  service:
    type: ClusterIP

  extraScrapeConfigs:
    - job_name: node-exporter
      kubernetes_sd_configs:
        - role: node
      relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        action: replace
        replacement: '${1}:9100'
        target_label: __address__
      - source_labels: [__meta_kubernetes_node_name]
        action: replace
        target_label: node
    - job_name: kube-state-metrics
      static_configs:
        - targets:
            - kube-state-metrics.monitor.svc.cluster.local:8080