alertmanager:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi

  ingress:
    enabled: true
    pathType: Prefix
    hostname: alertmanager.prometheus.local
    ingressClassName: nginx
  
  service:
    type: ClusterIP

server:
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  ingress:
    enabled: true
    pathType: Prefix
    hostname: prometheus.local
    ingressClassName: nginx
  
  service:
    type: ClusterIP
