kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: worker
- role: worker
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: 80
    protocol: TCP
  - containerPort: 30443
    hostPort: 443
    protocol: TCP
networking:
  kubeProxyMode: "ipvs"
  podSubnet: "10.0.0.0/16"
  serviceSubnet: "10.1.0.0/16"
